### PR TITLE
feature: Usage of outputIndex

### PR DESCRIPTION
**Pull request by gbarkhatov**
Adds usage of `outputIndex` for unbonding tx

### CODE REVIEW

**Comment by vitsalis** [comment]
Can you remove the styling/linting fixes? Let's keep this PR focused on the fix it performs, we can do the styling fixes in another PR.

**Comment by gbarkhatov** [comment]
@vitsalis done

**Review by vitsalis — APPROVED** [review]
Given that the unbonding transaction is standardized (i.e. has only one input and output), we should explore removing the `outputIndex` parameters for transactions that spend the unbonding output of the unbonding transaction, as the index of the unbonding output will always be 0.

**Comment by gbarkhatov** [comment]
@vitsalis removed withdrawal output index

**Review by vitsalis — APPROVED** [review]

**Pull request merged**
